insert into bestellingen(besteldatum, klantId, betaald, betalingsCode, betaalwijzeId, annulatie, annulatiedatum,
                         terugbetalingscode, bestellingsStatusId, actiecodeGebruikt, bedrijfsnaam, btwNummer,
                         voornaam, familienaam, facturatieAdresId, leveringsAdresId)
values('2026-05-20 10:30:00',
       1,
       1,
       'ABC123',
       1,
       0,
       null,
       null,
       1,
       0,
       'VDAB',
       'BE0123456789',
       'Jan',
       'Peeters',
       1,
       1);